# Generated by Django 5.0 on 2026-01-19 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(help_text='Formato: ABC123 o AB123CD', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de patente inválido. Use formato argentino (ej: ABC123 o AB123CD)', regex='^[A-Z]{2,3}\\d{3}[A-Z]{0,2}$')], verbose_name='Patente')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('engine_type', models.CharField(blank=True, help_text='Ej: 1.6 Nafta, 2.0 Diesel', max_length=50, null=True, verbose_name='Tipo de Motor')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN/Nº Chasis')),
                ('current_mileage', models.IntegerField(default=0, help_text='En kilómetros', verbose_name='Kilometraje Actual')),
                ('notes', models.TextField(blank=True, help_text='Observaciones especiales del vehículo', null=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='crm.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='crm_custome_phone_eb81ab_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_custome_last_na_bdc9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='crm_vehicle_plate_9788c2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['customer'], name='crm_vehicle_custome_810c30_idx'),
        ),
    ]
