# Generated by Django 5.0 on 2026-01-14 18:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('ACEITE', 'Aceite'), ('FILTRO_AIRE', 'Filtro de Aire'), ('FILTRO_ACEITE', 'Filtro de Aceite'), ('FILTRO_COMBUSTIBLE', 'Filtro de Combustible'), ('OTROS', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('min_stock', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('unit', models.CharField(choices=[('LITRO', 'Litro'), ('UNIDAD', 'Unidad'), ('PACK', 'Pack')], default='UNIDAD', max_length=10, verbose_name='Unidad de Medida')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='inventory_p_code_a06c9c_idx'), models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo/Observaciones')),
                ('reference', models.CharField(blank=True, help_text='Ej: Orden de servicio #123', max_length=100, null=True, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
