# Generated by Django 5.0 on 2026-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
