# Generated by Django 5.0 on 2026-01-20 20:26

from django.db import migrations


def update_movement_types(apps, schema_editor):
    """Actualizar ENTRADA -> COMPRA y SALIDA -> VENTA"""
    StockMovement = apps.get_model('inventory', 'StockMovement')
    
    # Actualizar ENTRADA a COMPRA
    StockMovement.objects.filter(movement_type='ENTRADA').update(movement_type='COMPRA')
    
    # Actualizar SALIDA a VENTA
    StockMovement.objects.filter(movement_type='SALIDA').update(movement_type='VENTA')


def reverse_movement_types(apps, schema_editor):
    """Revertir COMPRA -> ENTRADA y VENTA -> SALIDA"""
    StockMovement = apps.get_model('inventory', 'StockMovement')
    
    # Revertir COMPRA a ENTRADA
    StockMovement.objects.filter(movement_type='COMPRA').update(movement_type='ENTRADA')
    
    # Revertir VENTA a SALIDA
    StockMovement.objects.filter(movement_type='VENTA').update(movement_type='SALIDA')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_update_movement_types'),
    ]

    operations = [
        migrations.RunPython(update_movement_types, reverse_movement_types),
    ]
